routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'Customer\HomeController@index');
Route::get('/localizacao', 'Customer\LocationController@index')->name('location');
Route::get('/estabelecimentos', 'Customer\InstituteController@index')->name('institute.index');
Route::get('/estabelecimento/{resourceId}', 'Customer\InstituteController@show')->name('institute.show');

Route::group(['as' => 'page.'], function () {
    Route::get('/quem-somos', 'Customer\PageController@about')->name('about');
    Route::get('/politicas-de-privacidade', 'Customer\PageController@policy')->name('policy');
    Route::get('/termos-de-uso', 'Customer\PageController@term')->name('term');
    Route::get('/fale-conosco', 'Customer\PageController@contact')->name('contact');
    Route::get('/perguntas-frequentes', 'Customer\PageController@commonQuestion')->name('common.question');
});
Route::group(['as' => 'register.'], function () {
    Route::group(['as' => 'step.'], function () {
        Route::get('/passo-1', 'Customer\RegisterController@firstStep')->name('first');
        Route::get('/passo-2', 'Customer\RegisterController@secondStep')->name('second');
        Route::get('/passo-3', 'Customer\RegisterController@thirdStep')->name('third');
        Route::get('/passo-4', 'Customer\RegisterController@fourthStep')->name('fourth');
        Route::get('/passo-5', 'Customer\RegisterController@fifthStep')->name('fifth');
    });
    Route::group(['as' => 'form.'], function () {
        Route::post('/passo-1', 'Customer\RegisterController@firstRegister')->name('first');
        Route::post('/passo-2', 'Customer\RegisterController@secondRegister')->name('second');
        Route::post('/passo-3', 'Customer\RegisterController@thirdRegister')->name('third');
        Route::post('/passo-4', 'Customer\RegisterController@fourthRegister')->name('fourth');
        Route::post('/passo-5', 'Customer\RegisterController@fifthRegister')->name('fifth');
    });
});

app/Http/Controllers/Customer/RegisterController.php
<?php

namespace App\Http\Controllers\Customer;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;
use App\Http\Requests\RegisterRequest;

class RegisterController extends Controller
{
    public function firstStep()
    {
        return view('customer.pages.register.step-1');
    }
    public function secondStep()
    {
        return view('customer.pages.register.step-2');
    }
    public function thirdStep()
    {
        return view('customer.pages.register.step-3');
    }
    public function fourthStep()
    {
        return view('customer.pages.register.step-4');
    }
    public function fifthStep()
    {
        return view('customer.pages.register.step-5');
    }

    public function firstRegister(RegisterRequest $request)
    {
        $owner = $request->except('_token');
        session(['owner' => $owner]);
        return redirect()->route('register.step.second');
    }
    public function secondRegister(RegisterRequest $request)
    {
        $carWash = $request->except('_token');
        // $dataPosition = [
        //     'geohash' => ["stringValue" => $geoHash],
        //     'geopoint' => ["geoPointValue" => (object) ["latitude" => $location->lat, "longitude" =>  $location->lng]]
        // ];

        // session(['position' => (object) $dataPosition]);
        session(['carWash' => $carWash]);
        return redirect()->route('register.step.third');
    }
    public function thirdRegister(RegisterRequest $request)
    {
        $bank = $request->except('_token');
        session(['bank' => $bank]);
        return redirect()->route('register.step.fourth');
    }
    public function fourthRegister(RegisterRequest $request)
    {
        if ($request->seguroPossui == "true") {
            $other = $request->except('_token', 'seguroPorqueContratar');
        } else {
            $other = $request->except('_token', 'seguroCobertura');
        }
        $owner = request()->session()->get("owner");
        $carWash = request()->session()->get("carWash");
        $bank = request()->session()->get("bank");
        $owner['aceitouContatoWhats'] = isset($owner['aceitouContatoWhats']) ? 'Sim' : 'Não';
        $dataPartner = [
            'owner' => $owner,
            'carWash' => $carWash,
            'bank' => $bank,
            'other' => $other,
        ];
        Mail::send('email.partner-register', ['data' => $dataPartner], function ($m) {
            $m->from('contato@carsup.com.br', 'CarsUp');
            $m->to('contato@carsup.com.br', 'CarsUp')->subject('Cadastro Parceiro');
        });
        return redirect()->route('register.step.fifth');
    }
}

resources/views/customer/pages/register/step-1.blade.php
@extends('customer.templates.default')
@section('title', 'Dados - Proprietário')

@section('description', 'Dados - Proprietário')

@section('content')

    <section class="steps">

        <div class="container">

            <div class="row">

                <div class="col-md-4">

                    <div class="box-hiring-steps">

                        <h2>Etapas do cadastro</h2>

                        <ul>

                            <li>
                                <div class="footsteps footsteps-active">1</div>
                                <h4 class="step-active">Dados - Proprietário</h4>
                            </li>

                            <li>
                                <div class="footsteps">2</div>
                                <h4>Dados - Lava Rápido</h4>
                            </li>

                            <li>
                                <div class="footsteps">3</div>
                                <h4>Dados Bancários</h4>
                            </li>

                            <li>
                                <div class="footsteps">4</div>
                                <h4>Finalizar Cadastro</h4>
                            </li>

                        </ul>

                    </div>

                </div>

                <div class="col-md-8">

                    <div class="box-content-pages">

                        <div class="row">

                            <div class="col-md-12">

                                <form action="{{ route('register.form.first') }}" method="post">
                                    @csrf
                                    <fieldset class="holder-data">

                                        <legend>Dados do titular</legend>

                                        <div class="row">
                                            <div class="col-sm-6">
                                                <x-input name="firstName" label="Nome" placeholder="Ex: João" />
                                            </div>

                                            <div class="col-sm-6">
                                                <x-input name="lastName" label="Sobrenome" placeholder="Ex: Santos Lima" />
                                            </div>
                                        </div>

                                        <div class="row">

                                            <div class="col-sm-6">
                                                <x-input name="email" type="email" label="E-mail" placeholder="Ex: joaolima@gmail.com" />
                                            </div>

                                            <div class="col-sm-6">
                                                <x-input name="phone" clazz="input-phone" label="Telefone" placeholder="Ex: (11) 98030-4060" />
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-sm-6">
                                                <x-input name="rg" label="RG" placeholder="Ex: 12.345.678-9" />
                                            </div>
                                            <div class="col-sm-6">
                                                <div class="form-group">
                                                    <x-input name="organ" label="Orgão Emissor" placeholder="Ex: SSP" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <x-input name="cpf" clazz="input-cpf" label="CPF" placeholder="Ex: 123.456.789-10" />
                                            </div>
                                        </div>
                                    </fieldset>

                                    <div class="box-radios">

                                        <div class="row">

                                            <div class="col-sm-12">

                                                <div class="form-group">

                                                    <label class="lbl-caracteristicas">
                                                        <input type="checkbox" checked id="aceitouContatoWhats"
                                                            class="form-control" name="aceitouContatoWhats">
                                                        <span class="checkmark checkfirst"></span>
                                                        Concordo em receber contato via Whatsapp para fins de
                                                        cadastro
                                                    </label>

                                                </div>

                                            </div>

                                        </div>

                                    </div>

                                    <div class="row">

                                        <div class="col-sm-4">

                                            <div class="form-group">

                                                <button class="form-control btn-form">Continuar</button>

                                            </div>

                                        </div>

                                        <div class="col-sm-4">

                                            <div class="form-group">

                                            <a class="back-register" href="{{url('/')}}">Voltar</a>

                                            </div>

                                        </div>

                                    </div>

                                </form>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </section>
@endsection

resources/views/customer/pages/register/step-3.blade.php
@extends('customer.templates.default')
@section('title', 'Dados - Bancários')

@section('description', 'Dados - Bancários')

@section('content')
    <section class="steps">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="box-hiring-steps">
                        <h2>Etapas do cadastro</h2>
                        <ul>
                            <li>
                                <div class="footsteps footsteps-completed">1</div>
                                <h4 class="step-completed">Dados - Proprietário</h4>
                            </li>
                            <li>
                                <div class="footsteps footsteps-completed">2</div>
                                <h4 class="step-completed">Dados - Lava Rápido</h4>
                            </li>
                            <li>
                                <div class="footsteps footsteps-active">3</div>
                                <h4 class="step-active">Dados Bancários</h4>
                            </li>
                            <li>
                                <div class="footsteps">4</div>
                                <h4>Finalizar Cadastro</h4>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="box-content-pages">
                        <div class="row">
                            <div class="col-md-12">
                                <form action="{{ route('register.form.third') }}" method="post">
                                    @csrf
                                    <fieldset class="holder-data">
                                        <legend>Dados Bancários</legend>
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <div class="form-group">
                                                    <label for="bank">Banco</label>
                                                    <select class="bank" name="bank" style="width: 100%;">
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <x-input name="agency" label="Agência (sem dígito)"
                                                    placeholder="Ex: 0097" />
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <x-input name="account" label="Conta" placeholder="Ex: 19780" />
                                            </div>
                                            <div class="col-sm-6">
                                                <x-input name="digit" label="Dígito" placeholder="Ex: 8" />
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <x-input name="cnpj" clazz="input-cnpj" label="CNPJ"
                                                    placeholder="Ex: 12.345.678/0000-12" />
                                            </div>
                                        </div>
                                        <div class="box-radios">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <label>Tipo de Conta</label>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-sm-5">
                                                    <div class="form-group">
                                                        <label class="lbl-caracteristicas">
                                                            <input type="radio" class="form-control" value="corrente"
                                                                name="type_count" checked>
                                                            <span class="checkmark"></span>
                                                            Conta Corrente
                                                        </label>
                                                    </div>
                                                </div>
                                                <div class="col-sm-5">
                                                    <div class="form-group">
                                                        <label class="lbl-caracteristicas"><input type="radio"
                                                                class="form-control" value="poupanca"
                                                                name="type_count"><span class="checkmark"></span>Conta
                                                            Poupança</label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </fieldset>
                                    <div class="row">
                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <button class="form-control btn-form">Continuar</button>
                                            </div>
                                        </div>
                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <a class="back-register" href="#">Voltar</a>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('scripts')
    <script type="text/javascript">
        $(document).ready(function() {

            axios.get(`{{ route('api.bank.index') }}`)
                .then(response => {
                    let banks = response.data;
                    let data = [];
                    banks.forEach((bank, item) => {
                        data.push({
                            id: bank.Code,
                            text: `${bank.Code} - ${bank.Name}`,
                        });
                    });
                    console.log(data);
                    $('.bank').select2({
                        data: data
                    });
                })
                .catch(response => {
                    console.log(response);
                });

        });

    </script>
@endsection

resources/views/customer/pages/register/step-4.blade.php
@extends('customer.templates.default')
@section('title', 'Dados - Finalizar Cadastro')

@section('description', 'Dados - Finalizar Cadastro')

@section('content')
    <section class="steps">

        <div class="container">

            <div class="row">

                <div class="col-md-4">

                    <div class="box-hiring-steps">

                        <h2>Etapas do cadastro</h2>

                        <ul>

                            <li>
                                <div class="footsteps footsteps-completed">1</div>
                                <h4 class="step-completed">Dados - Proprietário</h4>
                            </li>

                            <li>
                                <div class="footsteps footsteps-completed">2</div>
                                <h4 class="step-completed">Dados - Lava Rápido</h4>
                            </li>

                            <li>
                                <div class="footsteps footsteps-completed">3</div>
                                <h4 class="step-completed">Dados Bancários</h4>
                            </li>

                            <li>
                                <div class="footsteps footsteps-active">4</div>
                                <h4 class="step-active">Finalizar Cadastro</h4>
                            </li>

                        </ul>

                    </div>

                </div>

                <div class="col-md-8">

                    <div class="box-content-pages">

                        <div class="row">

                            <div class="col-md-12">

                                <form action="{{ route('register.form.fourth') }}" method="post">
                                    @csrf
                                    <fieldset class="holder-data">

                                        <legend>Finalizar Cadastro</legend>

                                        <div class="row">

                                            <div class="col-sm-12">
                                                <x-input name="password" label="Senha de login no painel" placeholder="Ex: •••••••" type="password" />
                                            </div>

                                        </div>

                                        <div class="row">

                                            <div class="col-sm-6">
                                                <x-input name="qtdLavaPorMes" label="Lavagens por mês" placeholder="Ex: 1200" />
                                            </div>

                                        </div>

                                        <div class="box-radios">

                                            <div class="row">

                                                <div class="col-sm-12">

                                                    <label>Possui seguro?</label>

                                                </div>

                                            </div>

                                            <div class="row">

                                                <div class="col-sm-5">
                                                    <div class="form-group">
                                                        <label class="lbl-caracteristicas"><input type="radio"
                                                                class="form-control seguroPossui" value="true" name="seguroPossui"
                                                                ><span class="checkmark"></span>Sim</label>
                                                    </div>
                                                </div>

                                                <div class="col-sm-5">
                                                    <div class="form-group">
                                                        <label class="lbl-caracteristicas"><input type="radio"
                                                                class="form-control seguroPossui" value="false"
                                                                name="seguroPossui"><span
                                                                class="checkmark"></span>Não</label>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="whySeguro" style="display:none;">
                                                <div class="row">
                                                    <div class="col-sm-6">
                                                        <div class="form-group">
                                                            <label>Pretende contratar seguro:</label>
                                                            <div class="row">
                                                                <div class="col-sm-5">
                                                                    <div class="form-group">
                                                                        <label class="lbl-caracteristicas"><input
                                                                                type="radio" class="form-control"
                                                                                name="seguroPretendeContratar"
                                                                                id="trueSeguroPretendeContratar"
                                                                                value="true"><span
                                                                                class="checkmark"></span>Sim</label>
                                                                    </div>
                                                                </div>
                                                                <div class="col-sm-5">
                                                                    <div class="form-group">
                                                                        <label class="lbl-caracteristicas"><input
                                                                                type="radio" class="form-control"
                                                                                name="seguroPretendeContratar"
                                                                                id="falseSeguroPretendeContratar"
                                                                                value="false"><span
                                                                                class="checkmark {{ $errors->has('falseSeguroPretendeContratar') ? 'is-invalid' : '' }}"></span>Não</label>
                                                                    </div>
                                                                    @if ($errors->has('firstName'))
                                                                        <span class="help-block">
                                                                            <small>{{ $errors->first('falseSeguroPretendeContratar') }}</small>
                                                                        </span>
                                                                    @endif
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-6">
                                                        <div class="form-group">
                                                            <label for="seguroPorqueContratar">Por que?</label>
                                                            <input type="text" name="seguroPorqueContratar"
                                                                id="seguroPorqueContratar" class="form-control">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="cover" style="display:none;">
                                                <div class="row">
                                                    <div class="col-sm-6">
                                                        <div class="form-group">
                                                            <label for="seguroCobertura">Valor de cobertura</label>
                                                            <input type="text" name="seguroCobertura" id="seguroCobertura"
                                                                class="form-control input-money">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-sm-12">
                                                <div class="form-group">
                                                    <label for="productClean">Fornecedor de produtos de limpeza</label>
                                                    <input type="text" id="productClean" class="form-control"
                                                        name="productClean" placeholder="Ex: Clean Master Ltda.">
                                                </div>

                                            </div>

                                        </div>

                                    </fieldset>

                                    <div class="row">

                                        <div class="col-sm-4">

                                            <div class="form-group">

                                                <button class="form-control btn-form">Cadastrar</button>

                                            </div>

                                        </div>

                                        <div class="col-sm-4">

                                            <div class="form-group">

                                                <a class="back-register" href="#">Voltar</a>

                                            </div>

                                        </div>

                                    </div>

                                </form>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </section>

@endsection

@section('scripts')
    <script type="text/javascript">
        $('.seguroPossui').on('change', function() {
            let seguroPossui = $(this).val();
            seguroPossuiValidate(seguroPossui);

        });
        $(document).ready(function() {
            let seguroPossui = $(this).val();
            seguroPossuiValidate(seguroPossui);
        });

        function seguroPossuiValidate(seguroPossui) {
            if (seguroPossui == 'false') {
                $('.whySeguro').slideDown();
                $('.cover').slideUp();
            } else if (seguroPossui == 'true') {
                $('.whySeguro').slideUp();
                $('.cover').slideDown();
            }
        }

    </script>
@endsection