routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'Customer\HomeController@index');
Route::get('/localizacao', 'Customer\LocationController@index')->name('location');
Route::get('/estabelecimentos', 'Customer\InstituteController@index')->name('institute.index');
Route::get('/estabelecimento/{resourceId}', 'Customer\InstituteController@show')->name('institute.show');

Route::group(['as' => 'page.'], function () {
    Route::get('/quem-somos', 'Customer\PageController@about')->name('about');
    Route::get('/politicas-de-privacidade', 'Customer\PageController@policy')->name('policy');
    Route::get('/termos-de-uso', 'Customer\PageController@term')->name('term');
    Route::get('/fale-conosco', 'Customer\PageController@contact')->name('contact');
    Route::get('/perguntas-frequentes', 'Customer\PageController@commonQuestion')->name('common.question');
});
Route::group(['as' => 'register.'], function () {
    Route::group(['as' => 'step.'], function () {
        Route::get('/passo-1', 'Customer\RegisterController@firstStep')->name('first');
        Route::get('/passo-2', 'Customer\RegisterController@secondStep')->name('second');
        Route::get('/passo-3', 'Customer\RegisterController@thirdStep')->name('third');
        Route::get('/passo-4', 'Customer\RegisterController@fourthStep')->name('fourth');
        Route::get('/passo-5', 'Customer\RegisterController@fifthStep')->name('fifth');
    });
    Route::group(['as' => 'form.'], function () {
        Route::post('/passo-1', 'Customer\RegisterController@firstRegister')->name('first');
        Route::post('/passo-2', 'Customer\RegisterController@secondRegister')->name('second');
        Route::post('/passo-3', 'Customer\RegisterController@thirdRegister')->name('third');
        Route::post('/passo-4', 'Customer\RegisterController@fourthRegister')->name('fourth');
        Route::post('/passo-5', 'Customer\RegisterController@fifthRegister')->name('fifth');
    });
});

app/Http/Controllers/Customer/CategoryController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    public function index()
    {

        $curl = curl_init();

        curl_setopt_array($curl, array(
            CURLOPT_URL => 'https://carsup-api.azurewebsites.net/v1/carwash',
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => '',
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 0,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => 'GET',
        ));

        $json = curl_exec($curl);

        curl_close($curl);
        $response = json_decode($json);
        $institutes = Institute::hydrate($response);
        return view('customer.pages.institute.index')
        ->with('institutes', $institutes);
    }
}

app/Http/Controllers/Customer/HomeController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Institute;

class HomeController extends Controller
{
    public function index()
    {
        // $api_url = config('services.api.url');
        // $responseCategories = requestCurl($api_url . 'categories') ?? [];

        // $categories = Category::hydrate($responseCategories)
        //     ->where('active', true);

        // $responseInstitutes = requestCurl($api_url . 'carwashes');
        // $institutes = $responseInstitutes ?
        // Institute::hydrate($responseInstitutes)
        //     ->where('active', true) :
        // (object) [];
        return view('customer.pages.home.index');
            // ->with('categories', $categories)
            // ->with('institutes', $institutes);
    }

}

app/Http/Controllers/Customer/InstituteController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use App\Models\Institute;

class InstituteController extends Controller
{
    public function index()
    {
        return view('customer.pages.institute.index');
    }
    public function show($resourceId)
    {
        $api_url = config('services.api.url');
        $response = requestCurl($api_url . 'carwash?id=' . $resourceId) ?? [];
        $responseServices = requestCurl($api_url . 'carwash/services?id=' . $resourceId) ?? [];
        return view('customer.pages.institute.show')
        ->with('institute', $response->data)
        ->with('services', $responseServices);
    }
}

app/Http/Controllers/Customer/LocationController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class LocationController extends Controller
{
    public function index()
    {
        return view('customer.pages.location.index');
    }
}

app/Http/Controllers/Customer/PageController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class PageController extends Controller
{
    public function about()
    {
        return view('customer.pages.about.index');
    }
    public function policy()
    {
        return view('customer.pages.policy.index');
    }
    public function term()
    {
        return view('customer.pages.term.index');
    }
    public function contact()
    {
        return view('customer.pages.contact.index');
    }
    public function commonQuestion()
    {
        return view('customer.pages.common-question.index');
    }
}

app/Http/Controllers/Customer/RegisterController.php
<?php

namespace App\Http\Controllers\Customer;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;
use App\Http\Requests\RegisterRequest;

class RegisterController extends Controller
{
    public function firstStep()
    {
        return view('customer.pages.register.step-1');
    }
    public function secondStep()
    {
        return view('customer.pages.register.step-2');
    }
    public function thirdStep()
    {
        return view('customer.pages.register.step-3');
    }
    public function fourthStep()
    {
        return view('customer.pages.register.step-4');
    }
    public function fifthStep()
    {
        return view('customer.pages.register.step-5');
    }

    public function firstRegister(RegisterRequest $request)
    {
        $owner = $request->except('_token');
        session(['owner' => $owner]);
        return redirect()->route('register.step.second');
    }
    public function secondRegister(RegisterRequest $request)
    {
        $carWash = $request->except('_token');
        // $dataPosition = [
        //     'geohash' => ["stringValue" => $geoHash],
        //     'geopoint' => ["geoPointValue" => (object) ["latitude" => $location->lat, "longitude" =>  $location->lng]]
        // ];

        // session(['position' => (object) $dataPosition]);
        session(['carWash' => $carWash]);
        return redirect()->route('register.step.third');
    }
    public function thirdRegister(RegisterRequest $request)
    {
        $bank = $request->except('_token');
        session(['bank' => $bank]);
        return redirect()->route('register.step.fourth');
    }
    public function fourthRegister(RegisterRequest $request)
    {
        if ($request->seguroPossui == "true") {
            $other = $request->except('_token', 'seguroPorqueContratar');
        } else {
            $other = $request->except('_token', 'seguroCobertura');
        }
        $owner = request()->session()->get("owner");
        $carWash = request()->session()->get("carWash");
        $bank = request()->session()->get("bank");
        $owner['aceitouContatoWhats'] = isset($owner['aceitouContatoWhats']) ? 'Sim' : 'Não';
        $dataPartner = [
            'owner' => $owner,
            'carWash' => $carWash,
            'bank' => $bank,
            'other' => $other,
        ];
        Mail::send('email.partner-register', ['data' => $dataPartner], function ($m) {
            $m->from('contato@carsup.com.br', 'CarsUp');
            $m->to('contato@carsup.com.br', 'CarsUp')->subject('Cadastro Parceiro');
        });
        return redirect()->route('register.step.fifth');
    }
}

resources/views/customer/includes/footer.blade.php
<footer>
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="box-footer">
                    <h3>CarsUp</h3>
                    <ul>
                        <li><a href="{{route('page.about')}}">Quem somos</a></li>
                        <li><a href="{{route('page.policy')}}">Política de Privacidade</a></li>
                        <li><a href="{{route('page.term')}}">Termos e condições de uso</a></li>
                        <li><a href="{{route('register.step.first')}}">Cadastre seu estabelecimento</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="box-footer">
                    <h3>Ajuda</h3>
                    <ul>
                        <li><a href="{{route('page.contact')}}">Fale conosco</a></li>
                        <li><a href="{{route('page.common.question')}}">Perguntas frequentes</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="social">
                    <a href="https://facebook.com/carsupapp" target="_blank">
                        <div class="box-midia-footer" style="background:#3e5b99;">
                            <i class="fab fa-facebook-f" aria-hidden="true"></i>
                        </div>
                    </a>
                    <a href="https://www.instagram.com/carsup/" target="_blank">
                        <div class="box-midia-footer" style="background:#f2b08d;">
                            <i class="fab fa-instagram" aria-hidden="true"></i>
                        </div>
                    </a>
                    <a href="https://www.youtube.com/channel/UCrVhmKSZkF_QXbjIwaY1Lrg" target="_blank">
                        <div class="box-midia-footer" style="background:#f00;">
                            <i class="fab fa-youtube" aria-hidden="true"></i>
                        </div>
                    </a>
                    <br>
                </div>
                <div class="msg-social">
                    <p>Nos sigam em nossas redes sociais</p>
                </div>
            </div>
        </div>
    </div>
    <div class="credit">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p>&copy; COPYRIGHT 2020 CARSUP. TODOS OS DIREITOS RESERVADOS.</p>
                </div>
            </div>
        </div>
    </div>
</footer>
</div>

resources/views/customer/includes/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<meta property="og:url" content="https://imaxinformatica.com.br/projetos/carsup-novo/" />
<meta property="og:title" content="CarsUp" />
<meta property="og:type" content="website" />
<meta property="og:description" content="O aplicativo certo para o seu negócio!" />
<meta property="og:image" content="https://imaxinformatica.com.br/projetos/carsup-novo/images/logo-og.jpg" />
<meta property="og:image:width" content="600" />
<meta property="og:image:height" content="600" />

<title>CarsUp</title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<link rel="apple-touch-icon" sizes="57x57" href="{{asset('images/favicon/apple-icon-57x57.png')}}">
<link rel="apple-touch-icon" sizes="60x60" href="{{asset('images/favicon/apple-icon-60x60.png')}}">
<link rel="apple-touch-icon" sizes="72x72" href="{{asset('images/favicon/apple-icon-72x72.png')}}">
<link rel="apple-touch-icon" sizes="76x76" href="{{asset('images/favicon/apple-icon-76x76.png')}}">
<link rel="apple-touch-icon" sizes="114x114" href="{{asset('images/favicon/apple-icon-114x114.png')}}">
<link rel="apple-touch-icon" sizes="120x120" href="{{asset('images/favicon/apple-icon-120x120.png')}}">
<link rel="apple-touch-icon" sizes="144x144" href="{{asset('images/favicon/apple-icon-144x144.png')}}">
<link rel="apple-touch-icon" sizes="152x152" href="{{asset('images/favicon/apple-icon-152x152.png')}}">
<link rel="apple-touch-icon" sizes="180x180" href="{{asset('images/favicon/apple-icon-180x180.png')}}">
<link rel="icon" type="image/png" sizes="192x192" href="images/favicon/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="{{asset('images/favicon/favicon-32x32.png')}}">
<link rel="icon" type="image/png" sizes="96x96" href="{{asset('images/favicon/favicon-96x96.png')}}">
<link rel="icon" type="image/png" sizes="16x16" href="{{asset('images/favicon/favicon-16x16.png')}}">
<link rel="manifest" href="{{asset('images/favicon/manifest.json')}}">
<meta name="msapplication-TileColor" content="#F58634">
<meta name="msapplication-TileImage" content="{{asset('images/favicon/ms-icon-144x144.png')}}">
<meta name="theme-color" content="#F58634">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link href="{{asset('plugins/fontawesome/css/all.min.css')}}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,900i&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="{{asset('css/app.css')}}?v=2.0.4">
<link href="{{asset('js/app.js')}}?v=1.0.0">

resources/views/customer/includes/header.blade.php
<header class="header">

    <div class="container">

        <div class="row">

            <div class="col-12">

                <a href="https://apps.apple.com/br/app/carsup/id1528913762"><img class="download-header" id="ios"
                        src="{{ asset('images/ios.png') }}" alt="Download IOS"></a>

                <a href="https://play.google.com/store/apps/details?id=br.com.carsup"><img class="download-header"
                        id="android" src="{{ asset('images/android.png') }}" alt="Download Android"></a>
                @if (false)
                    <div class="box-delivery">
                        <span>ENDEREÇO</span>
                        <a href="{{ route('location') }}" class="location"><img src="{{ asset('images/place.png') }}"
                                alt="Icon"></a>
                    </div>
                @endif
                <ul class="main-menu">
                    <li><a href="{{ route('register.step.first') }}" id="register">Cadastrar estabelecimento</a></li>

                    <li><a href="https://portal.carsup.com.br/" target="_blank" id="login">Entrar</a></li>
                </ul>
            </div>
        </div>

    </div>



    <button class="btn-menu-toggle" type="button">
        <div class="row-menu-toggle"></div>
        <div class="row-menu-toggle"></div>
        <div class="row-menu-toggle"></div>
    </button>

    <div id="menu-mobile">
        <div class="box-title-menu-mob">
            <strong>Menu</strong>
            <button id="btn-close-menu"><i class="fas fa-long-arrow-alt-right"></i></button>
        </div>

        <ul id="main-menu-mobile">
            <li><a href="{{ route('register.step.first') }}" id="register">Cadastrar estabelecimento</a></li>
            <li><a href="https://portal.carsup.com.br/" id="login">Entrar</a></li>
            <li><a href="https://apps.apple.com/br/app/carsup/id1528913762"><img class="download-header-mobile" id="ios"
                        src="{{ asset('images/ios.png') }}" alt="Download IOS"></a>
            </li>
            <li><a href="https://play.google.com/store/apps/details?id=br.com.carsup"><img
                        class="download-header-mobile" id="android" src="{{ asset('images/android.png') }}"
                        alt="Download Android"></a></li>

        </ul>
    </div>
</header>

resources/views/customer/includes/scripts.blade.php
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"
    integrity="sha256-0YPKAwZP7Mp3ALMRVB2i8GXeEndvCq3eSl/WsAl1Ryk=" crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
</script>

<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

<!-- Input Mask e Mask money -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.3.4/jquery.inputmask.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-maskmoney/3.0.2/jquery.maskMoney.min.js"></script>
<script src="{{asset('js/mask.js')}}"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script type="text/javascript">

    /*$(document).scroll(function() {

        var scrollTop = $(window).scrollTop();

        if (scrollTop > 200 ) {

            $('.menu-scroll').css('display', 'block');

        }

        else{

            $('.menu-scroll').css('display', 'none');

        }

    });*/

    $(document).ready( function(){
        let locationSession = sessionStorage.getItem('location');
        let locationData = JSON.parse(locationSession);
        $('.location').append(locationData.address);
    });

    $(document).on('click', '#scroll', function(event) {
        var tela = $(window).width();
        if (tela < 768) {
            event.preventDefault();
            $('html, body').animate({
                scrollTop: $($.attr(this, 'href')).offset().top - 20
            }, 800);
        } else {
            event.preventDefault();
            $('html, body').animate({
                scrollTop: $($.attr(this, 'href')).offset().top - 180
            }, 800);
        }
    });

    $('.slider-carousel').slick({
        prevArrow: $('.prev-carousel'),
        nextArrow: $('.next-carousel'),
        slidesToShow: 6,
        slidesToScroll: 1,
        autoplay: false,
        autoplaySpeed: 2500,
        pauseOnHover: false,
        responsive: [{
            breakpoint: 768,
            settings: {
                slidesToShow: 3
            }
        }, {
            breakpoint: 520,
            settings: {
                slidesToShow: 2
            }
        }]
    });

    $('.slider-testimonial').slick({
        prevArrow: $('.prev-carousel-testimonial'),
        nextArrow: $('.next-carousel-testimonial'),
        slidesToShow: 4,
        slidesToScroll: 1,
        autoplay: true,
        autoplaySpeed: 6500,
        pauseOnHover: false,
        responsive: [{
            breakpoint: 768,
            settings: {
                slidesToShow: 1
            }
        }, {
            breakpoint: 520,
            settings: {
                slidesToShow: 1
            }
        }]
    });
    $('.btn-menu-toggle').click(function() {
        $('#menu-mobile').show('slide', {
            direction: 'right'
        }, 1000);
    });

    $('#btn-close-menu').click(function() {
        $('#menu-mobile').hide('slide', {
            direction: 'right'
        }, 1000);
    });
</script>